### PR TITLE
Refactor to service

### LINKED ISSUE #108: Refactor code that can be shared between directives into a service

### LINKED ISSUE #129: Legend do not reload after changing to different /route and returning to map.
Hi,
I have an app with many factories, that use a map with same layers. When I go to the detail of a factory, I display an automatically centered map with the lat long values stored in the database with different layers.
My problem is that legend load only once, when I go back an choose an other factory the legend don't reload (it is empty), even if it is the same map with the same layers (just the extant change).
I'm working with the beta 5, and the legend work well on refreshing when I show/hide layers.
Any idea? Maybe I must refresh the legend when the extent of the map changes?

### PR DESCRIPTION
**Pull request by tomwayson**
@jwasil please review.

In particular, I'm interested in your thoughts on how the map and layer objects are now instantiated from the directive linker functions (instead of from the controller constructors). I did this b/c the infoTemplate directive's link function needed to modify the layer options before the layer was created. However, it introduces a subtle, but possibly significant change to the timing of things b/c [directive controller constructors are run top town and linker functions are run bottom up](http://www.bennadel.com/blog/2603-directive-controller-and-link-timing-in-angularjs.htm). So it used to be:

1. create map
2. create layers and add to map
3. add info template(s) to layer options (did not get applied)

Now it's:

1. add info templates to layer options
2. create layers and add to map (once map deferred resolves)
3. create map

I'm not a big fan of this, but it was the easiest way to deal w/ the info template issue. I think another way would be to move the map/layer construction back to the controllers and then have the info template directive modify the info template _after_ the layer has been created using [setInfoTemplate](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#setinfotemplate) or in the case of dynamic map service layers, [setInfoTemplates](https://developers.arcgis.com/javascript/jsapi/arcgisdynamicmapservicelayer-amd.html#setinfotemplates).

If you agree, I'll try it that way and if it works, add a follow up commit to this PR.

Resolves #108
Resolves #129

### CODE REVIEW

**Comment by tomwayson** [comment]
Also, @jwasil, this is probably going to break #132 (sorry).

59c9173adbf3fa97a21e22cf358e58f956099679 is probably going to affect the dynamic map services example page and I changed the name of the `esriMapUtils.addCustomBasemap()` function. After this is merged, I'll go in and make the necessary updates.

**Comment by jwasil** [comment]
@tomwayson this is looking really, really great. Thanks for all your work on this one!

I have been stepping through the changes, but still want some more time with this one. I see that the **esriLegend** is acting funny when it is a fresh page load vs. a router navigation, and the timing is as follows:
a. If a fresh page load, or first time via a router: map is created, and then **esriLegend** `link` method is accessed.  Success.
b. If subsequent page navigation via a router: esriLegend link method is accessed _before_ map is created, and then `mapController.getMap()` doesn't actually have a valid `mapDeffered.promise` to return. Failure.
I'm in the middle of updating and experimenting with the **esriLegend**, but if you have some thoughts, go for it.

Regarding the commit I just pushed, the only changes of note were in **esriMapUtils**.  Hope you don't mind that I worked in `angular.forEach()` for readability; they do their own `hasOwnProperty` checks anyways.  Nit-picky, I know, I know.

**Comment by jwasil** [comment]
Also,
> If you agree, I'll try it that way and if it works, add a follow up commit to this PR.

I like that idea, and think it is worth trying out.  Might make for an easier flow to explain to others. Might also help us better understand the whole timing issue with **esriLegend** (and maybe establish another pattern for that one, too), which was also happening with setInfoTemplate also not being an available property/method in some routing cases.

**Comment by jwasil** [comment]
Ok, @tomwayson I'm not sure what to think of the timing differences when routing and starting up the **esriLegend**.  The way I tackle map-dependent dijits in other scenarios is to wait until the map's `load` event fires.  Could we look into that as a unique pattern for these kinds of directives which wrap map-dependent dijits?

I just pushed another commit which is just some general cleanup for the **esriLegend**.  Doesn't solve our current problem, but thought it would help us along our way.  Nothing too substantial: removed an unused dependency, using our $destroy pattern instead of dijit registry, and perhaps 1 or 2 items that are unneeded, like bindToController.

**Comment by tomwayson** [comment]
I'm pulling back from the idea of initiating the map/layer objects in the linker function.This seems to be the cause of the issue w/ the legend not working the second time around. For now I've moved the construction of the map object back to the map controller's constructor. More work to do to move the layers back.

**Comment by jwasil** [comment]
Really glad to hear you identified and fixed the legend timing symptom!

**Comment by RobertLycksell** [comment]
Great pull request. Now I can understand the demos and have a working app based on the angular map:)

**Comment by tomwayson** [comment]
@jwasil

Would appreciate if you could make one final review. 

I've:
* moved the code that instantiates the layer objects back to the controller contructors
* changed the`setInfoTemplate()` 
In particular the notion of adding named controllers for the directives and moving any non-shared, implementation specific code back from the util services to the controllers.

If this

**Comment by jwasil** [comment]
@tomwayson thanks for your patience while I looked this one over.  I like where you're headed with these changes, and I have gotten a better sense for it too with the other changes you pointed on your fork.  The idea with separate named controllers is a good one, and I agree that this is a great effort for helping out with the goal of making it more straightforward for users to roll their own directives.  I don't think I have any other suggestions or changes to suggest at the moment.  Bring it in!

**Pull request merged**
