### PR TITLE
fixes bug w/ JSAPI 4.7+ by using .when() instead of .then()

### PR DESCRIPTION
**Pull request by tomwayson**
- Choose the appropriate base branch that you want to merge into:
  - **v1.x** for v1 (Esri JSAPI 3.x)
  - **master** for v2 (Esri JSAPI 4.x)

master

- Describe the proposed changes:
  - Is there an example or test page to demonstrate any new or changed features?
  - Does your PR include appropriate unit or functional tests for source code alterations?

fixes bug w/ JSAPI 4.7+ by using .when() instead of .then()
also defaults to 4.8
unit tests pass, but I can't get e2e to run
also removes "esri-loader is preferred for Angular (2+)" from README

- Provide a reference to any related issue.
#350

### CODE REVIEW

**Review by andygup — CHANGES_REQUESTED** [review]
LGTM, thanks! One additional thought => If we are saying that the repo is in maintenance mode we should update the compatibility table to put a cap on the JS API versions (3.x and 4.x).

For example, in the `v1.0.0` row we would update the JS API column to say `v3.12 - v3.25`. Another example for the `v2.0.2` row we would update the JS API column to `v4.0 - v4.8`.

The implication is this is this last time we would update this repo. On a related note, I also want to see if we can remove the AngularJS sample in the JS API either at 4.9 for 4.10...

Thoughts?

**Comment by tomwayson** [comment]
Good ideas all around @andygup.

Honestly, if we remove the sample from the API docs (and we should), we don't _need_ to do this update at all - we could just cap the compat table as you suggest.

That said, the deed is (mostly) done, so I'll update the table, cut a release, and leave it to you to update or remove the sample from the SDK.

**Comment by andygup** [comment]
Sounds like a plan 👍

**Comment by jwasilgeo** [comment]
Me, lurking: nice work @tomwayson and @andygup!  Thanks for doing this round of maintenance.

**Pull request merged**
