### PR TITLE
Allow to use a variable for webmapid attribute

### PR DESCRIPTION
**Pull request by stephguignard**
- Choose the appropriate base branch that you want to merge into:
  - **v1.x** for v1 (Esri JSAPI 3.x)

- Describe the proposed changes:
The webmapid have to be hardcoded in the html template file, with this change we can pass a variable and then this variable **mapSurface.mapConfig.webmapId** will be evaluated.
It is easier for the configuration when we use multiple webmapid in the same application.

For example  :
```html
<esri-map id="map" webmap-id="{{mapSurface.mapConfig.webmapId}}" item-info="itemInfo" load="mapSurface.mapLoaded">
</esri-map>
```

### CODE REVIEW

**Comment by tomwayson** [comment]
Thanks @stephguignard 

Would you mind providing a test page that demonstrates the new functionality? You could copy the [existing web map test page](https://github.com/Esri/angular-esri-map/blob/b222a10f9315e9a9e730195e643a8e5d67a50a01/test/web-map.html) and update it to pull the web map from the scope instead of being an inline attribute.

If you feel ambitious, you could also add the corresponding e2e test by copying the [web map spec](https://github.com/Esri/angular-esri-map/blob/b222a10f9315e9a9e730195e643a8e5d67a50a01/test/e2e/specs/web-map.js) as well. If you don't feel up to that, we can add that.

**Comment by stephguignard** [comment]
Hi @tomwayson 

Ok, I created files (example and test)

My usecase for this parameter is not to change webmap id on the same view. If someone need this functionality, they must change the code in **EsriMapController.js** to destroy the map before to load the new one.

In my application, I use the tag **<esri-map>** inside my own directive and I have several different webmapid in different views.

BR,
Stéph.

**Comment by jwasilgeo** [comment]
Hi @stephguignard,

Thank you for opening this PR with the requested changes to the v1 code.  I reviewed and tested out your changes and they're a very helpful contribution.  I just have two tiny requests for you:
- Can you please change the filename of your spec .js file to have the exact same filename as your new test .html file?
- Would you be OK with removing [these 2](https://github.com/Esri/angular-esri-map/pull/297/files#diff-b3df156b1fad303f918ada637c42fc4dR48) commented lines (48,49)? 

Thanks, and after that I can take care of merging.

**Comment by stephguignard** [comment]
Hi @jwasilgeo,

I did the changes.

Thanks,
Stéph.

**Comment by jwasilgeo** [comment]
@stephguignard thank you!

**Pull request merged**
