### PR TITLE
replaced about page with patterns pages

### LINKED ISSUE #155: add patterns page to site
Cover the following and link to relevant example/test pages:
- [ ] getting a reference to the map object (load event and registry)
- [ ] lazy load JSAPI
- [ ] roll your own directive
- [ ] add custom basemap in route's resolve (would need to update test page to work this way)?

### PR DESCRIPTION
**Pull request by tomwayson**
resolves #155 

@jwasil please review

### CODE REVIEW

**Comment by jwasil** [comment]
@tomwayson this is great!  Awesome new additions with helpful, interesting content to read over.  I think it is ready to merge as-is; however, just 1 small consideration: maybe add a left nav or breadcrumbs to the patterns' child pages?  Not sure if it would be worth it or actually be a little too much, up to you.  :+1:

**Comment by tomwayson** [comment]
@jwasil thanks for the suggestion. added left-nav (w/ routes, titles coming from config) and some code snippets.

**Comment by jwasil** [comment]
@tomwayson awesome additions to an already awesome PR!  But, I'm not seeing the new code snippets in the live gh-pages.  It might be that it wants a `.` or some other magic combination of `.`'s at the beginning of the relative paths?  I remember running into the exact same thing when wiring up `<a>`'s between the example and test pages.

**Comment by tomwayson** [comment]
Thanks! fixed.

**Comment by jwasil** [comment]
:shipit: !!

**Pull request merged**
