### PR TITLE
esriRegistry for v2

### LINKED ISSUE #255: v2 esriRegistry
Explore and see what it'll take to port it from v1 and bring it into v2.

### PR DESCRIPTION
**Pull request by jwasilgeo**
@tomwayson please review.  Thanks for your help earlier!

Resolves #255

### CODE REVIEW

**Comment by tomwayson** [comment]
Nice work. Example page looks good!

Can you update the changelog and then we'll merge.

**Comment by jwasilgeo** [comment]
Thanks. Done!

**Comment by jwasilgeo** [comment]
@tomwayson actually hold on until I commit again and let you know. The scene view needs to have a mobile browser check on it.

**Comment by jwasilgeo** [comment]
Ok, @tomwayson one more review, please!

**Comment by tomwayson** [comment]
Great. Thanks for the extra effort.

**Pull request merged**
