### PR TITLE
Update esriLegend.js to watch for changes to layerInfos; add dynamicmapservicelayer directive and infoTemplate directive.

### PR DESCRIPTION
**Pull request by Kollibri**
This update uses scope.$watchCollection to watch map.layerInfos for changes and refresh the legend appropriately.

### CODE REVIEW

**Comment by Kollibri** [comment]
Also added commit for issue #44 to this pull request.

**Comment by tomwayson** [comment]
Thanks @Kollibri!

Looks like some useful additions that I would like to merge.

Generally speaking tho, I'd prefer to deal w/ these enhancements each in their own PR since they do not appear to be linked (unless I'm missing something). Would you be willing to make separate PRs for each? If that's too much of a hassle let me know, and I'll see if I can split them up by the commits.

**Comment by Kollibri** [comment]
@tomwayson I will see if I can get it split up.  I'm still a bit new to github and originally I tried to do this as two separate PRs but it merged them into one.  But I will work on trying to separate these.

**Comment by tomwayson** [comment]
@Kollibri thanks. Yes, if you make any more commits on a branch w/ an open PR and then push those commits, they will get added to the existing PR. Ideally, each of these features would be developed in separate branches, and then you could make separate PRs.

However, in this case I can see that the commit w/ updates to the legend (d7f8620) is a parent of the commit w/ the dyn map service/info template (0ececb1) and they are both in master, so it's going to be a little tricky to split. I would say don't worry about it unless you want to teach yourself some git commands.

I can figure out a way to test them separately and merge them as is.

**Comment by jwasil** [comment]
Awesome work, all!! :+1:

**Pull request merged**
