### PR TITLE
314 angular 1.6.0 view options

### LINKED ISSUE #319: Test with Angular v1.6.0+ (master branch)
Related to #314.  This issue is for the **master (v2) angular-esri-map** branch.

e2e functional tests will go over a suite of Angular pre-v1.6.0 (ONCE) **and** Angular v1.6.0+ to make sure any controller code changes to support the `$compile`'s `$onInit()` work for older and newer Angular versions.

See [here](https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-services-$compile) and the part about:

> If you are writing a library, you need to change your code as shown above. Furthermore, if your library also targets versions before 1.5 (which do not support the $onInit() lifecycle hook), you may need to manually call $onInit() from your constructor...

### PR DESCRIPTION
**Pull request by jwasilgeo**
resolves #319 
relates to #314 for master branch (I still have to apply the src code changes to v1 branch before that issue is fully resolved)

### CODE REVIEW

**Comment by tomwayson** [comment]
I did not get a chance to look into those failing protractor tests. @jwasilgeo do the same tests fail for you?

**Comment by jwasilgeo** [comment]
I don't think I hadn't those working either, and my suspicion is focused on the delayed/async nature of those tests. (As we know, getting protractor to delay and slow itself down has been moderately painful.) Shall we continue with them or shut off the tests?

**Comment by tomwayson** [comment]
I pulled the latest but I still get this error:

```
1) Popups should how a popup when the feature layer is clicked on
  Message:
    Expected 'esri-invisible esri-popup esri-widget' to equal 'esri-popup esri-widget'.
```

**Comment by jwasilgeo** [comment]
Thanks for checking @tomwayson.  I'm not seeing it yet but I'll have the opportunity to look a little deeper on another forthcoming PR.

**Pull request merged**
