### PR TITLE
Calcite bootstrap

### PR DESCRIPTION
**Pull request by jwasil**
@tomwayson please review.

- introduces calcite-bootstrap
  - had trouble with npm and gulp copy to site css, not sure how to get the 100% of necessary glyphicon and font resources which don't appear to be part of calcite-bootstrap dist
- removed icons from ngdocs nav pills after experimenting with icons in the primary site nav pills; it seemed a little too busy
- upgraded to newest version of highlight.js and switched to "github" syntax theme, and switched to making the snippets tabs `ng-show` instead of `ng-if` because there was a bit too much of scroll position jumping
- You can uncomment the last section of **main.css** to see what a _rough_ implementation of an angularjs brand colors theme might look like.  I may have leaned too heavily in the red direction.

Once we agree on the final touches on this, I'll shift focus to the left nav for examples (#98).

### CODE REVIEW

**Comment by jwasil** [comment]
resolves #77

**Comment by tomwayson** [comment]
looks great @jwasil!

I uncommented the angular colors w/ a slight mod.

Can you follow up the left nav on this same branch/PR and then we'll merge?

**Comment by jwasil** [comment]
Thanks for taking a look at how this is so far, and the hover/focus css change is definitely better. I'll continue on left nav on this branch.

**Comment by jwasil** [comment]
@tomwayson just pushed the new "examples-left-nav".  Needs just a bit of cleanup to get rid of flashing on home page when sites app is starting up, and perhaps fine-tuning of colors during hover and "active" state?  Just putting this out there if you get a chance to take a look.  Otherwise, I'll be back on here later to poke around some more.

**Comment by jwasil** [comment]
^ oh and legend columns aren't wide enough. Might be a couple other oddities to sort out.

**Comment by tomwayson** [comment]
Looking great!

**Comment by jwasil** [comment]
Alright, here we go!  One final check please, if you don't mind, and then if it looks good please go ahead and merge.  Also, feel free to make any changes whatsoever or to request additional items.  The only things I'm still wondering about are the base and hover colors of the left nav.

**Comment by tomwayson** [comment]
excellent work @jwasil!

**Comment by jwasil** [comment]
:hand:-5!

**Pull request merged**
