### PR TITLE
Added additional JavaScript API attributes

### PR DESCRIPTION
**Pull request by eas604**
`angular-esri-map` only supported a few ESRI JavaScript API attributes by default. I needed to support a few more in a project I'm working on, so I added most of the attributes:

`attributionWidth, autoResize, displayGraphicsOnPan, fadeOnZoom, fitExtent, force3DTransforms,
logo, maxScale, maxZoom, minScale, minZoom, nav, navigationMode, optimizePanAnimation,
resizeDelay, scale, showAttribution, showInfoWindowOnClick, slider, sliderOrientation,
sliderPosition, sliderStyle, smartNavigation, wrapAround180`

You can see several of these directives in `test/additional-attributes.html`.

### CODE REVIEW

**Comment by tomwayson** [comment]
Thanks @eas604!

I've tried these changes locally, and they work well and don't break the existing API.

However, it seems that most of these attributes are only used at map creation time, and therefore it would be better to read them from `$attrs` instead of having them bound to the isolated scope. For example, see how the [map directive checks for an extent](https://github.com/Esri/angular-esri-map/blob/master/src/directives/esriMap.js#L76).  

So, even though it is [not our goal to have 1 to 1 parity w/ the JSAPI functionality](http://esri.github.io/angular-esri-map/#/about), I'm inclined to merge this if it's modified to read the map options from `$attrs`.  Would like to hear thoughts from @patrickarlt, @dbouwman, @jabadia, @mpriour as well.

**Comment by eas604** [comment]
Sounds good to me. I actually originally had the attributes in `$attrs`, and it won't be a problem to switch.

**Comment by eas604** [comment]
Attributes have been moved to `$attrs`. Please let me know if there's anything else I can do.

**Comment by tomwayson** [comment]
Nice work @eas604.

Would you mind squashing those commits? (You asked...) Once that's done I'll verify and merge unless I hear any objection from the others.

Thanks!

**Comment by eas604** [comment]
Squashed! Thanks @tomwayson

**Pull request merged**
