### PR TITLE
chaining promises additional promise

### PR DESCRIPTION
**Pull request by jwasilgeo**
@tomwayson there's no github issue associated with this, but I worked up a small optional fix for behavior I noticed recently in Firefox and IE for the chaining promises example.  Check out the commit description for more info.  A drawback is that this departs from the JSAPI example.  Any thoughts or reasons to forget and deny this?

### CODE REVIEW

**Comment by tomwayson** [comment]
Do you see this same behavior in the JSAPI sample page in IE/Firefox? If so, best option is to leave as is and notify JSAPI team.

**Comment by jwasilgeo** [comment]
Good question. I'm not really seeing it happen (works fine).  I can even keep on nesting `return view.then(function() {` in the sandbox in FF without a hiccup.  Sandbox doesn't fire up at all for me in IE11. Meh...maybe this PR isn't worth it for now.

**Comment by tomwayson** [comment]
Leave it open and revisit after 4.0 is out of beta.

**Comment by jwasilgeo** [comment]
Let's cancel this, it appears to be fine at 4.0 from what I can see in the test page.

**Pull request closed without merging**
