### PR TITLE
V2beta2 examples

### LINKED ISSUE #196: v2 functional tests
Once we figure out what test pages to include (#194), let's write some protractor tests for them!

### LINKED ISSUE #212: New sample page for Bookmarks (v2beta2)
Create a new sample page for [bookmarks](https://developers.arcgis.com/javascript/beta/sample-code/webscene-slides/index.html)

  This should ideally include:
- [x] test page
- [x] functional tests
- [x] example page in the gh-pages site
- [x] deal with info in comment below

Originates from #194.

### LINKED ISSUE #213: New sample page for extrude polygon (v2beta2)
Create a new sample page for [Extrude](https://developers.arcgis.com/javascript/beta/sample-code/polygon-extrusion-3d/index.html).  This should ideally include:
- [x] test page
- [x] functional tests
- [x] example page in the gh-pages site

Originates from #194.

### LINKED ISSUE #214: New sample page for elevation (v2beta2)
Create a new sample page for [Elevation](https://developers.arcgis.com/javascript/beta/sample-code/scene-toggle-elevation/index.html).  This should ideally include:
- [x] test page
- [x] functional tests
- [x] example page in the gh-pages site

Originates from #194.

### LINKED ISSUE #215: New sample page for search (v2beta2)
Create a new sample page for [Search](https://developers.arcgis.com/javascript/beta/sample-code/widgets-search-2d/index.html).  This should ideally include:
- [x] test page
- [x] functional tests
- [x] example page in the gh-pages site

Originates from #194.

### LINKED ISSUE #216: New sample page for chaining promises (v2beta2)
Create a new sample page for [chaining promises](https://developers.arcgis.com/javascript/beta/sample-code/chaining-promises/index.html).  This should ideally include:
- [x] test page
- [x] functional tests
- [x] example page in the gh-pages site

Originates from #194.

### LINKED ISSUE #217: New sample page for geodesic buffers (v2beta2)
Create a new sample page for [Geodesic buffers](https://developers.arcgis.com/javascript/beta/sample-code/ge-geodesicbuffer/index.html).  This should ideally include:
- [x] test page
- [x] functional tests
- [x] example page in the gh-pages site

Originates from #194.

### LINKED ISSUE #218: New sample page for vector tiles (v2beta2)
Create a new sample page for [vector tiles](https://developers.arcgis.com/javascript/beta/sample-code/layers-vectortilelayer/index.html).  This should ideally include:
- [x] test page
- [x] functional tests
- [x] example page in the gh-pages site

Originates from #194.

### PR DESCRIPTION
**Pull request by jwasil**
@tomwayson please review. This branch introduces a slew of new test pages, example pages, and e2e tests.  This covers the following issues, but there are a few caveats:

- #211: Only partially complete, we'll have to do something about the offset popups with JSAPI. Maybe disable it for now in the examples site?
- Resolves #212 
- Resolves #213 
- Resolves #214 
- Resolves #215 
- Resolves #216 
- Resolves #217: The placement of both views and the "based on" sample link at the bottom was difficult to place and position correctly on the standalone test page (by following the JSAPI sample page as closely as possible); however, it seems fine as a part of the examples site and calcite.
- Resolves #218
- Resolves #196

926a24b reverses a right float change from #192. I found that on small screens, the snippets div actually gets moved out of place and offset too much to the left when browsing examples. We can revisit a fix for that, if we see what was described in that issue, if the left nav becomes really short again.

And, just for a few housekeeping reminders, this PR includes merged/closed PRs #220 and #221, and is fully concerned with milestone v2-beta.2.

### CODE REVIEW

**Comment by jwasil** [comment]
I went ahead and just pushed a final commit that also resolves #224 to add the property binding to the examples site.  I think that commit also finally fixes the examples site snippets column alignment.

**Comment by tomwayson** [comment]
@jwasil impressive work.

I've done a review, and everything looks perfect. Only issue is that I get one failing functional test for popups. Is that expected given the known bug w/ pop ups? If so we should skip it w/ `xdescrbe()`.

**Comment by jwasil** [comment]
Thanks for the review of this big old PR!  Yes, that should fail for now with what we know about popups.  Do we also want to hide it from the examples page (comment out from appConfig.js?)

**Comment by tomwayson** [comment]
Good idea, let's do that as well. Please push a commit w/ those changes and I'll merge.

**Comment by jwasil** [comment]
Cool, thanks for the feedback.  Good to go.

**Pull request merged**
