### PR TITLE
FeatureLayer url attribute

### PR DESCRIPTION
**Pull request by willisd2**
This commit allows the url attribute on the FeatureLayer directive to accept either a url or a scope variable that holds the url value.  Again, my apologies, this request contains both of my previous commits...

### CODE REVIEW

**Comment by willisd2** [comment]
I noticed that the minified version of this directive wasn't working.  I included a fix for that in this pull request.

**Comment by tomwayson** [comment]
@willisd2 

w/r/t getting the feature layer url from scope (instead of in-lined in the attribute), is there a reason that we can't just use something like `url="{{myScopeObj.url}}"`?

For example, see: http://jsfiddle.net/tomwayson/1kb54dxo/

**Comment by willisd2** [comment]
Not 100% sure at the moment.  I was trying to play around with it on that fiddle, but it's a little quirky and only seems to work with a full page reload.  I think the reason I went down that route was because it allows your url attribute to be dynamic.  In otherwords, if your scope variable for the url is tied to a <select> element that allows you to select a different url, it will pick up on that and load whatever new feature layer was selected.

**Comment by tomwayson** [comment]
Good point. Updating the scope variable will not update the layer in the current implementation. See: http://jsfiddle.net/tomwayson/1kb54dxo/8/

However, unless I'm missing something (entirely possible), I don't see a watch or anything in this PR that would enable that behavior either.

At this point, I'm thinking a better way to handle updating layers would be #51. If that works for you, I think we can close this PR (since the other commits you made have already been merged).

If you are still interested in the behavior of being able to change a layer's URL after it's been added to the map (instead of adding/removing layers as in #51) then please open a new issue or PR.

Thanks again for your contributions!

**Comment by tomwayson** [comment]
@willisd2 I've merged #51, which allows binding the `url` variable to either a string literal or a scope variable, so I'm closing this PR.

**Pull request closed without merging**
