### PR TITLE
draft vector tile directive with example

### PR DESCRIPTION
**Pull request by snodnipper**
quick stab at adding a vector tile directive.  Perhaps this is something folk can refine?

I note that the lifecycle doesn't behave quite right - I seem to need to click onto, say, 'Set Basemap' before 'Vector Basemap'.  Perhaps someone can comment.

Happy to rebase as necessary.

### CODE REVIEW

**Comment by tomwayson** [comment]
@snodnipper 

Thank you for this thorough contribution (including docs!). I definitely plan to merge this, but I've been seeing the same issues you mention above and haven't had time to dig into it yet.

@jwasil this is on the roadmap now, so whomever gets a chance to work on it first should just self-assign this PR.

**Comment by snodnipper** [comment]
No worries Tom - glad you found it useful.  I will be keen to see what the issue is.

**Comment by jwasil** [comment]
@snodnipper I'd like to echo @tomwayson's comment: thanks for your work on this!  I have been investigating and have some thoughts on what is causing this.  I'll let you know when I have some commits of some changes worth mentioning pretty soon.

**Comment by jwasil** [comment]
Refer to #182 for more info.

**Comment by tomwayson** [comment]
Thanks agains @snodnipper!

**Comment by snodnipper** [comment]
Np guys!  Happy Christmas and may 2016 be full of Angular 2 gorgeousness!

**Pull request merged**
