### PR TITLE
added a link to an ionic2 sample

### PR DESCRIPTION
**Pull request by andygup**
Proposed changes:
- One minor addition to README
- Adds one new link to an Ionic2 sample under the What about Angular 2? section.

### CODE REVIEW

**Comment by jwasilgeo** [comment]
Thanks @andygup!  I'd say this relates to #263.

We could also make another section in the README to point our venerable readers to the ionic1 sample repo and your ionic2 repo.  What do you think?  Or is it better not to even mention ionic1 at this point in time and keep things lean in the README?

**Comment by andygup** [comment]
Definitely relates to that issue.

I'm happy to create a subsection and include both. New projects should use Ionic[latest], but there are still quite a few Ionic1 projects out there.

**Comment by andygup** [comment]
@jwasilgeo take a look at this [diff](https://github.com/Esri/angular-esri-map/compare/master...andygup:add_link?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8R151) when you get a chance.

**Comment by jwasilgeo** [comment]
Looks good to me! Anything else? Shall we also close out the related issue?

**Comment by andygup** [comment]
Looks good, I can't think of anything else at the moment. Yep, let's go ahead and close out #263 as well. Thanks!

**Pull request merged**
