### PR TITLE
v2 defaults to JSAPI 4.1

### LINKED ISSUE #299: missing closing </ul> bracket
#### Expected behavior

A small error in the documentation.  In the pop-up template, there should be a closing bracket for element <ul>.  Sorry, it's really minor I am sure the DOM still renders.

#### Actual behavior

List elements are contained within two opening <ul> brackets.

#### Steps to reproduce the behavior

http://esri.github.io/angular-esri-map/#/examples/popups

look within the 'content' property of the PopupTemplate object.

### LINKED ISSUE #305: default to JSAPI 4.1 (master branch)
Update master branch to use 4.1.
- [x] **src/core/esriLoader.js** and **test/unit/core/esriLoader.spec.js** default to 4.1
- [x] docs site **index.html** to 4.1
- [x] update existing samples based on 4.1 official sample changes
- [x] update README
  - [x] quick start code
  - leave dependencies table alone
- [x] update CHANGELOG

### PR DESCRIPTION
**Pull request by jwasilgeo**
- Choose the appropriate base branch that you want to merge into:
  - **master** for v2 (Esri JSAPI 4.x)

resolves #305 
resolves #299 

@tomwayson do you have available bandwidth for a review of this PR?

Once approved and merged, I can take care of:
- [ ] deploying latest docs to gh-pages
- [ ] cutting a new v2.0.1 release

### CODE REVIEW

**Comment by tomwayson** [comment]
nice work @jwasilgeo!

Unfortunately, popups still look borked to me. I pulled this branch, ran `npm i && gulp` and I see this in Chrome:

popup-no-bueno

Also a problem in the extrusion example:

image

It's been a long time since I got my BA in Geography, but I'm pretty sure that ain't Jefferson, MS.

I suspect those problems are w/ the ArcGIS API for JavaScript itself, and not related to angular-esri-map, but haven't done any testing to confirm that.

Speaking of testing. Unit tests pass, but thanks to the joys of local webdriver testing, I'm not able to run the e2e tests. I'm sure they pass if you say they do.

Other than that, great work on this PR in not only updating to 4.1 but updating the examples to show the new (if still broken) functionality.

**Comment by tomwayson** [comment]
My bad, that may indeed be Jefferson, MS. I thought I was looking at a map of the entire US, but turns out that data is just from a few southern states. It truly _has_ been a while since I got that geography degree.

**Comment by jwasilgeo** [comment]
@tomwayson thanks for the review!  I just made some changes to a couple of the e2e functional tests that were not passing I think because they were too fast for a few dom elements that needed some more time to become available.

I think the popup issue is still there with JSAPI.  I just tried out the [related sample page](https://developers.arcgis.com/javascript/latest/sample-code/sandbox/sandbox.html?sample=get-started-popupTemplate) and did this in the `style` tag.  If you then scroll down to the map view (hopefully it isn't just me) you'll see the borky popups.

```css
html,
body {
  padding: 0;
  margin: 0;
  height: 10000px;
  width: 100%;
}
#viewDiv {
  margin-top:800px;
  height: 300px;
}
```

What do you think?  Shall we still press forward?

**Comment by tomwayson** [comment]
Yeah, I did the same last night. Did you see something, like in the [release notes](https://developers.arcgis.com/javascript/latest/guide/release-notes/) that gave you the impression that popups would be fixed? If so, we should let'em know they're not.

Either way, I think we should remove that example from the nav menu for now, but otherwise merge your changes.

Also, w/r/t e2e tests not working for me, it's a webdriver issue in my env that I don't have time to figure out. As long as they're passing for you, let's roll w/ this.

**Comment by jwasilgeo** [comment]
I went back and tested out the behavior in our sample docs with jsapi 4.0, and still saw the same effects.  Good idea: we can indeed log feedback to that team to let them know what we're seeing.  I just pushed another commit that hides the PopupTemplate sample from our TOC and router.

**Pull request merged**
