### PR TITLE
Api docs continued

### LINKED ISSUE #99: Docs need an API section
Need to document API of every service/directive.

May want to wait until after #69

### PR DESCRIPTION
**Pull request by jwasil**
@tomwayson please review and refer to our mighty to-do checklist at https://github.com/Esri/angular-esri-map/issues/99#issuecomment-155486184.  Resolves #99 once the checklist is done.

Fyi I went ahead and checked "on" **core/esriMapUtils** for you, but for anyone else reading this, that is currently over in the **more-unit-tests** branch.

I think we've just got to coordinate on documenting **core/esriRegistry**.  Any chance that's also coming hand-in-hand with its unit tests?

Thanks!

### CODE REVIEW

**Comment by jwasil** [comment]
@tomwayson can you also take a look at https://github.com/Esri/angular-esri-map/blob/master/src/map/esriMap.js#L23 for me?  That param, and the rest of the params (like are some of them really `Expression` types?) could use some editing I think.  Thanks!

**Comment by jwasil** [comment]
Update: I also added a 1st rough draft of a navTemplate to the ngdocs, and a (admittedly rough) css override for some of our longer controller names in the left nav list.  This relates to https://github.com/Esri/angular-esri-map/issues/99#issuecomment-155481778 for the docs site, not for the main gh-pages site.

**Comment by tomwayson** [comment]
@jwasil I made some changes to the directive params in response to your questions above. I also added a home page to the site and got the two nav menus (ngdocs and rest of site) synced up. I'll add esriRegistry and merge shortly.

**Comment by jwasil** [comment]
Wonderful, thanks!

**Pull request merged**
