### PR TITLE
Feature layer events

### LINKED ISSUE #103: Feature layer events
The feature layer directive should expose via attribute function binding (at least) the [load](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#event-load) event of the feature layer so that users can get a handle to the feature layer object. May also want to expose the [update-end event](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#event-update-end) as well.

This should be accompanied by a new example page similar to the [Map Events](http://esri.github.io/angular-esri-map/#/examples/map-events) page.

### PR DESCRIPTION
**Pull request by jwasil**
@tomwayson please review.  Includes test page, e2e spec, and new docs example page.  If this all checks out, just a reminder to please update gh-pages as well.  Thanks!  Resolves #103.

### CODE REVIEW

**Comment by jwasil** [comment]
PS: added a new floorFilter to help with how we split up the examplePages in the ng-repeats in examples.html; see 6772e61 on this PR.

**Comment by tomwayson** [comment]
@jwasil this looks great, and could be merged as is, unless you want to spend any time looking at my comment on the floor filter.

FYI - I want these same events for the dynamic map service layer, but at this point, I'm going to wait to refactor to see if we can get those events "for free."

**Comment by jwasil** [comment]
- Agree with the floorFilter comment. I'll be happy to take it to the next level and make it work for us to be a bit more convenient.
- Cool, I was wondering about the dynamic layer events as well. Glad to hear your thoughts on that. I'm on the same page. :-D

**Comment by tomwayson** [comment]
Great.

I'm half way though the dyamic map service events and the related portion of the refactor right now, so I'll probably just include that in this PR.

So, I'll wait to merge until after you've pushed an updated filter and I've pushed the dynamic map service events and the new `esriMapUtils` factory.

**Comment by jwasil** [comment]
Awesome, I'm excited to see what's coming.  Just pushed 4d0e350 and I think that satisfies you needing to wait on me, so long as you're down with what I cooked up for the flooring stuff. You've got the green :traffic_light:!

**Pull request merged**
