### PR TITLE
v2 and jsapi4: src, test pages, docs site

### LINKED ISSUE #211: New sample page for popups (v2beta2)
Create a new sample page for [popups](https://developers.arcgis.com/javascript/beta/sample-code/get-started-popup/index.html).  This should ideally include:
- [x] test page
- [x] functional tests
- [x] example page in the gh-pages site
- [x] deal with info in comment below

Originates from #194.

### PR DESCRIPTION
**Pull request by jwasilgeo**
@tomwayson please review.

This is the second PR as part of a larger effort to get this repo ready with JSAPI 4.0 release.  Please reference #278 for a full TO DO list.  This PR's branch is different than, but continues from, the branch in PR #281.  This starts at fc849ee.

Here you can expect to find updates to:
- docs site example pages
  - finally showing the popups example, which resolves #211
  - updates to the home button directive, since clicks were not being triggered in the example page; the solution was to wire up an `ng-click` in the home button directive's template (instead of `link` func)
- docs site patterns pages (mainly links back to jsapi docs)
- some test pages, for consistency with their corresponding example pages

### CODE REVIEW

**Comment by tomwayson** [comment]
@jwasilgeo 

nice work! Changes look good to me, but it's a lot to review, so I brushed over a lot.

Also, when I tried to run locally, mixed content errors prevent a few of the examples from running b/c Chrome hates developers, and I haven't had time to set up the cert for my new machine, yet. It's mostly the examples under the 3D section, if they run for you, then that's good. Also, I wasn't able to run the e2e tests b/c Selenium hates America and I need to get chromedriver or something installed on my new machine. 

So, if the site and tests are running for you, I'd say merge it.

Both of the issues I'm having w/ my new machine show that we need better [dev instructions](https://github.com/Esri/angular-esri-map#development-instructions), package.json devDependencies, or both, but that's an issue for another day.

**Comment by jwasilgeo** [comment]
Tom, thanks for looking over this.  Do you have any other details on the mixed content issues?  I just saw a mixed content error in the console for the "WebScene Slides" example page, but it also exists in the same way for the Esri JSAPI example page.  I don't see other examples being obviously affected or blocked when running locally (Chrome 50, Windows 7).

**Comment by tomwayson** [comment]
So, I can run through all the example pages (now on newly merged master) in FireFox and Safari w/ no problems. However, in Chrome, many things are broken, and I _think_ it's b/c Chrome doesn't like my local cert and blocks a lot of the functionality (pretty much nothing happens when I click on any buttons or checkboxes).

**Comment by jwasilgeo** [comment]
Weird, sorry you are experiencing that. Right now crossing my fingers it is just your new dev environment. Didn't see that on (now deleted) my own temp fork's gh-pages with the latest stuff either. I'll continue to keep an eye out.

**Pull request merged**
